application: kopf-kultur
version: 1
runtime: go
api_version: go1

handlers:
- url: /api/.*
  script: _go_app#

- url: /
  static_files: static/public/index.html
  upload: static/public/index.html
- url: /static
  static_dir: static
- url: /admin/
  static_files: static/admin/index.html
  upload: static/admin/index.html
